# Generated by Django 3.0.6 on 2020-06-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Div',
            new_name='Division',
        ),
    ]
