# Generated by Django 3.0.6 on 2020-06-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0003_auto_20200601_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
