# Generated by Django 3.0.6 on 2020-06-03 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexpage', '0004_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('secondname', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_divisions', to='indexpage.Division')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_professions', to='indexpage.Profession')),
            ],
            options={
                'ordering': ('firstname', 'secondname'),
            },
        ),
    ]
